repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
      - id: check-yaml
        exclude: mkdocs.yml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: check-json
      - id: check-ast
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v1.2.3
      hooks:
          - id: flake8
            args: ["--ignore=E203,W503,E501", "--per-file-ignores=__init__.py:F401"]
    #- repo: https://github.com/pre-commit/mirrors-mypy
      #rev: v0.782
      #hooks:
         #- id: mypy
           #args: [--ignore-missing-imports]
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          name: isort (python)
    - repo: https://github.com/psf/black
      rev: 23.1.0
      hooks:
      - id: black
    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.0 # Fill in a tag / sha here
      hooks:
      - id: gitlint
